### ISSUE TITLE
What more can you offer?

### ISSUE THREAD

**Issue by jdboyd-github** [oats-group3/General-Work#18]
What sets you apart from Amazon? On Amazon you can find products of any quality, and with its customer base, a cheaper overall price. What is something that makes your company different?

**Comment by cvaska** [comment]
We only sell quality items, so you don't need to worry about playing the Amazon "crap, ripoff, or legit" lottery when you order something. When you order from us, you can rest easy knowing what you bought is legit and of good quality.
