### ISSUE TITLE
Differentiating low quality products from high quality products

### ISSUE THREAD

**Issue by davidlentsch** [oats-group3/General-Work#19]
How will your business differentiate between low quality products that are available and high quality products? Will you create a persona of every customer to determine what goods are best for them? Will you have curation guidelines for different personas?

**Comment by cvaska** [comment]
The items are curated in general, without regard to personal preferences. There will be a set guide for deciding what belongs and what doesn't. Personalization will be done with an algorithm that picks from the pre-curated items.
