### ISSUE TITLE
Customers

### ISSUE THREAD

**Issue by d-jo** [oats-group3/General-Work#9]
One potential revenue stream would be to charge businesses to apply for a spot in the catalog. After paying a fee and the product being reviewed, it would be added to the catalog. Alinder could be business-to-business as well as providing end-customers a high-quality curated catalog.

Declan

**Comment by cvaska** [comment]
That is a possible business idea, but we wouldn't want our reviews to be biased based on being paid by the manufacturer, so it this time we are focusing on direct to consumer selling subsidized by advertisements from trusted partners.
